# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Repositories\ReDian\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(QtCore.QSize(350, 140))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectFilesButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectFilesButton.setObjectName("selectFilesButton")
        self.horizontalLayout.addWidget(self.selectFilesButton)
        self.lineEditFiles = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditFiles.setReadOnly(True)
        self.lineEditFiles.setObjectName("lineEditFiles")
        self.horizontalLayout.addWidget(self.lineEditFiles)
        self.labelFilesNum = QtWidgets.QLabel(self.centralwidget)
        self.labelFilesNum.setObjectName("labelFilesNum")
        self.horizontalLayout.addWidget(self.labelFilesNum)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.processButton = QtWidgets.QPushButton(self.centralwidget)
        self.processButton.setObjectName("processButton")
        self.horizontalLayout_2.addWidget(self.processButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "热点处理器 v0.1"))
        self.selectFilesButton.setText(_translate("MainWindow", "选择文件"))
        self.labelFilesNum.setText(_translate("MainWindow", "共0个文件"))
        self.processButton.setText(_translate("MainWindow", "处理并保存"))
